# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'area2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class A2_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1060, 600)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1061, 601))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 1061, 591))
        self.label.setStyleSheet("background-image: url(:/area2_bg.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.frame_10 = QtWidgets.QFrame(self.frame)
        self.frame_10.setGeometry(QtCore.QRect(191, 100, 401, 301))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label1_13 = QtWidgets.QLabel(self.frame_10)
        self.label1_13.setGeometry(QtCore.QRect(0, 0, 401, 301))
        self.label1_13.setText("")
        self.label1_13.setObjectName("label1_13")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(321, 490, 91, 21))
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label1_14 = QtWidgets.QLabel(self.frame)
        self.label1_14.setGeometry(QtCore.QRect(381, 440, 101, 16))
        self.label1_14.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label1_14.setText("")
        self.label1_14.setObjectName("label1_14")
        self.frame_11 = QtWidgets.QFrame(self.frame)
        self.frame_11.setGeometry(QtCore.QRect(621, 100, 401, 301))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.label1_15 = QtWidgets.QLabel(self.frame_11)
        self.label1_15.setGeometry(QtCore.QRect(0, 0, 401, 301))
        self.label1_15.setText("")
        self.label1_15.setObjectName("label1_15")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(751, 490, 91, 21))
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label1_16 = QtWidgets.QLabel(self.frame)
        self.label1_16.setGeometry(QtCore.QRect(811, 440, 101, 16))
        self.label1_16.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label1_16.setText("")
        self.label1_16.setObjectName("label1_16")
        self.pushButton_15 = QtWidgets.QPushButton(self.frame)
        self.pushButton_15.setGeometry(QtCore.QRect(0, 50, 157, 65))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setStyleSheet("background-image: url(:/first_button.png);\n"
"font: 75 12pt \"Cascadia Code\";\n"
"font: 75 14pt \"Modern\";\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"微软雅黑\";")
        self.pushButton_15.setObjectName("pushButton_15")

        self.retranslateUi(Dialog)
        self.pushButton_15.clicked.connect(Dialog.gomain) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_15.setText(_translate("Dialog", "返回"))
import data.a
