# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'area1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class A1_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1060, 600)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1060, 600))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 1061, 601))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-image: url(:/area1_bg.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setGeometry(QtCore.QRect(190, 100, 401, 301))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label1_1 = QtWidgets.QLabel(self.frame_6)
        self.label1_1.setGeometry(QtCore.QRect(0, 0, 401, 301))
        self.label1_1.setText("")
        self.label1_1.setObjectName("label1_1")
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setGeometry(QtCore.QRect(620, 100, 401, 301))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label1_3 = QtWidgets.QLabel(self.frame_7)
        self.label1_3.setGeometry(QtCore.QRect(0, 0, 401, 301))
        self.label1_3.setText("")
        self.label1_3.setObjectName("label1_3")
        self.label1_4 = QtWidgets.QLabel(self.frame)
        self.label1_4.setGeometry(QtCore.QRect(380, 440, 101, 16))
        self.label1_4.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label1_4.setText("")
        self.label1_4.setObjectName("label1_4")
        self.label1_5 = QtWidgets.QLabel(self.frame)
        self.label1_5.setGeometry(QtCore.QRect(810, 440, 101, 16))
        self.label1_5.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label1_5.setText("")
        self.label1_5.setObjectName("label1_5")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(320, 490, 91, 21))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(750, 490, 91, 21))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame)
        self.pushButton_7.setGeometry(QtCore.QRect(0, 50, 157, 65))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("background-image: url(:/first_button.png);\n"
"font: 75 12pt \"Cascadia Code\";\n"
"font: 75 14pt \"Modern\";\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"微软雅黑\";")
        self.pushButton_7.setObjectName("pushButton_7")

        self.retranslateUi(Dialog)
        self.pushButton_7.clicked.connect(Dialog.gomain) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_7.setText(_translate("Dialog", "返回"))
import data.a
