# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'enter_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class E_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1055, 593)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1060, 600))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 1061, 601))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("background-image: url(:/enter_bg.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(-1, 50, 157, 65))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-image: url(:/first_button.png);\n"
"font: 75 12pt \"Cascadia Code\";\n"
"font: 75 14pt \"Modern\";\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"微软雅黑\";")
        self.pushButton.setObjectName("pushButton")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(190, 100, 401, 301))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label1 = QtWidgets.QLabel(self.frame_2)
        self.label1.setGeometry(QtCore.QRect(0, 0, 401, 301))
        self.label1.setText("")
        self.label1.setObjectName("label1")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(620, 100, 401, 301))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label2 = QtWidgets.QLabel(self.frame_3)
        self.label2.setGeometry(QtCore.QRect(0, 0, 401, 301))
        self.label2.setText("")
        self.label2.setObjectName("label2")
        self.label3 = QtWidgets.QLabel(self.frame)
        self.label3.setGeometry(QtCore.QRect(300, 440, 101, 16))
        self.label3.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label3.setText("")
        self.label3.setObjectName("label3")
        self.label4 = QtWidgets.QLabel(self.frame)
        self.label4.setGeometry(QtCore.QRect(720, 440, 101, 16))
        self.label4.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label4.setText("")
        self.label4.setObjectName("label4")
        self.label5 = QtWidgets.QLabel(self.frame)
        self.label5.setGeometry(QtCore.QRect(300, 490, 101, 16))
        self.label5.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label5.setText("")
        self.label5.setObjectName("label5")
        self.label6 = QtWidgets.QLabel(self.frame)
        self.label6.setGeometry(QtCore.QRect(720, 490, 111, 16))
        self.label6.setText("")
        self.label6.setObjectName("label6")

        self.retranslateUi(Dialog)
        self.pushButton.clicked.connect(Dialog.gomain) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "返回"))
import data.a
